<?php
namespace CarloNicora\Minimalism\MinimaliserData\Enums;

use CarloNicora\Minimalism\MinimaliserData\Objects\TableObject;

Enum Generator
{
    case Builders;
    case AbstractBuilders;
    case Databases;
    case DataObjects;
    case Factories;
    case IO;
    case AbstractIO;
    case CreatorValidators;
    case UpdaterValidators;
    case Models;
    case Caches;
    case AbstractCaches;
    case ChildModels;
    case NodeApi;
    case NodeApiInterface;

    /**
     * @param TableObject $table
     * @return string
     */
    public function getFileName(
        TableObject $table,
    ): string
    {
        if ($this === self::NodeApi){
            return $this->name . '.ts';
        }
        
        if ($this === self::NodeApi || $this === self::NodeApiInterface){
            return $this->name . 'Interface.ts';
        }
        
        $response = match ($this){
            self::Builders => $table->getObjectName() . 'Builder',
            self::AbstractBuilders => 'Abstract' . $table->getObjectName() . 'Builder',
            self::Databases => $table->getObjectNamePlural() . 'Table',
            self::DataObjects => $table->getObjectName(),
            self::Factories => $table->getObjectNamePlural() . 'factory',
            self::IO => $table->getObjectName() . 'IO',
            self::AbstractIO => 'Abstract' . $table->getObjectName() . 'IO',
            self::CreatorValidators => $table->getObjectName() . 'CreateValidator',
            self::UpdaterValidators => $table->getObjectName() . 'EditValidator',
            self::Models, self::ChildModels => $table->getObjectNamePlural(),
            self::Caches => $table->getObjectNamePlural() . 'CacheFactory',
            self::AbstractCaches => 'Abstract' . $table->getObjectNamePlural() . 'CacheFactory',
        };

        return $response . '.php';
    }

    public function overrides(
    ): bool {
        return match($this) {
            self::Builders, self::Caches, self::IO, self::Models, self::ChildModels => false,
            default => true,
        };
    }

    /**
     * @param TableObject $table
     * @return string
     */
    public function getDataSubfolder(
        TableObject $table,
    ): string
    {
        $response = match ($this){
            self::AbstractBuilders, self::AbstractIO, self::AbstractCaches => 'Data' . DIRECTORY_SEPARATOR . $table->getObjectNamePlural() . DIRECTORY_SEPARATOR . 'AutoGenerated' . DIRECTORY_SEPARATOR . 'Abstracts',
            self::CreatorValidators, self::UpdaterValidators, self::Databases, self::DataObjects, self::Factories => 'Data' . DIRECTORY_SEPARATOR . $table->getObjectNamePlural() . DIRECTORY_SEPARATOR . 'AutoGenerated',
            self::Builders, self::IO, self::Caches => 'Data' . DIRECTORY_SEPARATOR . $table->getObjectNamePlural(),
            self::Models => $this->name,
            self::ChildModels => self::Models->name . DIRECTORY_SEPARATOR . $table->getObjectNamePlural(),
            self::NodeApi => '..'. DIRECTORY_SEPARATOR .'node'. DIRECTORY_SEPARATOR .'api',
            self::NodeApiInterface => '..'. DIRECTORY_SEPARATOR .'node'. DIRECTORY_SEPARATOR .'api'. DIRECTORY_SEPARATOR . 'interfaces',
        };

        return $response . DIRECTORY_SEPARATOR;
    }
}